// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYr7XEWKVoPg7FiZFMIwKXaJfVFXOChY',
    appId: '1:912959242254:web:3a3ea814603cb38135fc5f',
    messagingSenderId: '912959242254',
    projectId: 'cutzclubmobileapp',
    authDomain: 'cutzclubmobileapp.firebaseapp.com',
    storageBucket: 'cutzclubmobileapp.appspot.com',
    measurementId: 'G-HPBR61SFJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4D7tHmMiIYQjDqlAXRibhQuQRtshz20I',
    appId: '1:912959242254:android:8af3a4098cd9af6435fc5f',
    messagingSenderId: '912959242254',
    projectId: 'cutzclubmobileapp',
    storageBucket: 'cutzclubmobileapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6P_j_-85PhRGeDJ9ZPdc42rtiN8Bl5V0',
    appId: '1:912959242254:ios:9224fde619d83cec35fc5f',
    messagingSenderId: '912959242254',
    projectId: 'cutzclubmobileapp',
    storageBucket: 'cutzclubmobileapp.appspot.com',
    iosClientId:
        '912959242254-9o2vfkoqhupudv73s6ef3490nv76grqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6P_j_-85PhRGeDJ9ZPdc42rtiN8Bl5V0',
    appId: '1:912959242254:ios:9224fde619d83cec35fc5f',
    messagingSenderId: '912959242254',
    projectId: 'cutzclubmobileapp',
    storageBucket: 'cutzclubmobileapp.appspot.com',
    iosClientId:
        '912959242254-9o2vfkoqhupudv73s6ef3490nv76grqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );
}
